name: MinuteIdeas
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  intl: ^0.18.1
  url_launcher: ^6.2.2
  provider: ^6.1.1
  infinite_scroll_pagination: ^4.0.0
  path_provider: ^2.1.1
  visibility_detector: ^0.4.0+2
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  fl_chart: ^0.66.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true

  assets:
    - assets/ideas.json
    - assets/categories.json
